#define DT_DRV_COMPAT gpio_ps2_pio

#include <hardware/pio.h>
#include <zephyr/drivers/misc/pio_rpi_pico/pio_rpi_pico.h>
#include "ps2_pio_rx.pio.h"     // Generated by pioasm
#include "ps2_pio_tx.pio.h"

struct ps2_pio_config {
    const struct device *pio_dev;
    PIO pio;
    uint pio_sm;
    uint scl_pin;
    uint sda_pin;
};

struct ps2_pio_data {
    struct ps2_driver_api api;
    uint pio_offset_rx;
    uint pio_offset_tx;
    struct k_work rx_work;
};

// PIO program definitions
RPI_PICO_PIO_DEFINE_PROGRAM(ps2_pio_rx, 0, 3,
    // ... instruction bytes ...
);

RPI_PICO_PIO_DEFINE_PROGRAM(ps2_pio_tx, 0, 5,
    // ... instruction bytes ...
);

static int ps2_pio_init(const struct device *dev) {
    struct ps2_pio_data *data = dev->data;
    const struct ps2_pio_config *config = dev->config;
    
    // Get PIO instance
    config->pio = pio_rpi_pico_get_pio(config->pio_dev);
    
    // Load RX program into PIO instruction memory
    data->pio_offset_rx = pio_add_program(config->pio, 
                                          RPI_PICO_PIO_GET_PROGRAM(ps2_pio_rx));
    
    // Configure RX state machine
    pio_sm_config sm_config = pio_get_default_sm_config();
    sm_set_in_pins(&sm_config, config->sda_pin);           // Read SDA
    sm_set_wait_pin(&sm_config, config->scl_pin);          // Wait on SCL
    
    pio_gpio_init(config->pio, config->scl_pin);
    pio_gpio_init(config->pio, config->sda_pin);
    gpio_set_dir(config->scl_pin, GPIO_IN);
    gpio_set_dir(config->sda_pin, GPIO_IN);
    
    pio_sm_init(config->pio, config->pio_sm, 
                data->pio_offset_rx, &sm_config);
    pio_sm_set_enabled(config->pio, config->pio_sm, true);
    
    // Setup work queue for processing RX data
    k_work_init(&data->rx_work, ps2_pio_rx_work_handler);
    
    return 0;
}

// IRQ handler: FIFO ready interrupt
static void ps2_pio_irq_handler(const struct device *dev) {
    struct ps2_pio_data *data = dev->data;
    
    // Schedule work to read FIFO data
    k_work_submit(&data->rx_work);
}

// Work handler: Extract bits and call PS/2 callback
static void ps2_pio_rx_work_handler(struct k_work *work) {
    struct ps2_pio_data *data = container_of(work, 
                                             struct ps2_pio_data, rx_work);
    const struct ps2_pio_config *config = dev->config;
    
    // Read 32-bit word from PIO RX FIFO
    // Contains ~3 PS/2 frames (11 bits each)
    uint32_t data_word = pio_sm_get(config->pio, config->pio_sm);
    
    // Extract individual bits and reconstruct PS/2 frames
    for (int i = 0; i < 11; i++) {
        uint8_t bit = (data_word >> i) & 1;
        ps2_rx_bit(dev, bit);  // Feed to frame reconstruction logic
    }
}

// Implement ps2_driver_api interface
static const struct ps2_driver_api ps2_pio_driver_api = {
    .config = ps2_pio_configure,
    .read = ps2_pio_read,
    .write = ps2_pio_write,
    .disable_callback = ps2_pio_disable_callback,
    .enable_callback = ps2_pio_enable_callback,
};

DEVICE_DT_INST_DEFINE(0, &ps2_pio_init, NULL, 
                      &ps2_pio_data, &ps2_pio_config,
                      POST_KERNEL, 45, &ps2_pio_driver_api);
