// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// ps2_tx //
// ------ //

#define ps2_tx_wrap_target 0
#define ps2_tx_wrap 17

static const uint16_t ps2_tx_program_instructions[] = {
            //     .wrap_target
    0xfc83, //  0: set    pindirs, 3      side 3     
    0xf702, //  1: set    pins, 2         side 1 [3] 
    0xb742, //  2: nop                    side 1 [3] 
    0xb742, //  3: nop                    side 1 [3] 
    0xb742, //  4: nop                    side 1 [3] 
    0xf000, //  5: set    pins, 0         side 0     
    0xf801, //  6: set    pins, 1         side 2     
    0xe028, //  7: set    x, 8                       
    0x2003, //  8: wait   0 gpio, 3                  
    0x6001, //  9: out    pins, 1                    
    0x2083, // 10: wait   1 gpio, 3                  
    0x0048, // 11: jmp    x--, 8                     
    0x2003, // 12: wait   0 gpio, 3                  
    0xe001, // 13: set    pins, 1                    
    0x2083, // 14: wait   1 gpio, 3                  
    0x2003, // 15: wait   0 gpio, 3                  
    0x2083, // 16: wait   1 gpio, 3                  
    0xe080, // 17: set    pindirs, 0                 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ps2_tx_program = {
    .instructions = ps2_tx_program_instructions,
    .length = 18,
    .origin = -1,
};

static inline pio_sm_config ps2_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ps2_tx_wrap_target, offset + ps2_tx_wrap);
    sm_config_set_sideset(&c, 3, true, false);
    return c;
}
#endif

