// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// ps2_rx //
// ------ //

#define ps2_rx_wrap_target 0
#define ps2_rx_wrap 6

static const uint16_t ps2_rx_program_instructions[] = {
            //     .wrap_target
    0x2003, //  0: wait   0 gpio, 3                  
    0xe02a, //  1: set    x, 10                      
    0x2083, //  2: wait   1 gpio, 3                  
    0x4001, //  3: in     pins, 1                    
    0x2003, //  4: wait   0 gpio, 3                  
    0x0042, //  5: jmp    x--, 2                     
    0x8020, //  6: push   block                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ps2_rx_program = {
    .instructions = ps2_rx_program_instructions,
    .length = 7,
    .origin = -1,
};

static inline pio_sm_config ps2_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ps2_rx_wrap_target, offset + ps2_rx_wrap);
    return c;
}
#endif

