manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: petejohanson
      revision: feat/pointers-move-scroll # This is the "God Tier" mouse branch
      import: app/west.yml
    #- name: zmk-ps2-uart-driver
      #remote: petejohanson
      #revision: main
  self:
    path: config